### ISSUE TITLE
mapbox-gl-export.umd.js throws Uncaught ReferenceError: Size is not defined

### ISSUE THREAD

**Issue by pcambra** [watergis/maplibre-gl-export#119]
I was using https://github.com/watergis/mapbox-gl-export which is now archived and the dist file from watergis.github.io/mapbox-gl-export/mapbox-gl-export.js which worked fine by including the script.

However, when including www.unpkg.com/@watergis/mapbox-gl-export@3.0.4/dist/mapbox-gl-export.umd.js instead, the code throws "Uncaught ReferenceError: Size is not defined", I see that there are differences between the two files but not sure what is causing the issue.

**Comment by JinIgarashi** [comment]
@pcambra Could you provide any sample source code to reproduce it?

There are quite a lot of changes between old repo and new repo. Mostly refactoring to make mapbox one to use the same source code from maplibre-gl-export. There might be some bugs produced by this refactoring.

There is an example code in the repo for CDN of mapbox-gl-export.
- https://github.com/watergis/maplibre-gl-export/blob/main/packages/mapbox-gl-export/index_cdn.html
- https://github.com/watergis/maplibre-gl-export/blob/main/packages/mapbox-gl-export/index_cdn.js

**Comment by pcambra** [comment]
Ah many thanks for the pointer, I was following the previous code in https://github.com/watergis/maplibre-gl-export/tree/main/packages/mapbox-gl-export#use-cdn

The code provide works great, thanks again

**Comment by JinIgarashi** [comment]
@pcambra Thank you for mentioning documentation error. I updated CDN usage in README for both maplibre and mapbox.
