### ISSUE TITLE
 No icons or images are output

### ISSUE THREAD

**Issue by 21601-kimura** [watergis/maplibre-gl-export#15]
**Describe the bug**
No icons or images are output.

error :
Image "***" could not be loaded. Please make sure you have added the image with map.addImage() or a "sprite" property in your style. You can provide missing images by listening for the "styleimagemissing" map event.

**To Reproduce**
Use LoadImage() and addImage()

**Expected behavior**
Icon or image is output.

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Google Chrome
 - Version latest

**Comment by JinIgarashi** [comment]
https://github.com/watergis/mapbox-gl-export/issues/31 is also the same issue with this one

**Comment by JinIgarashi** [comment]
@21601-kimura I am sorry for the late reply. Thank you for fixing the bug.I have released as [v1.3.3](https://github.com/watergis/maplibre-gl-export/releases/tag/v1.3.3).
