### ISSUE TITLE
TypeError: i2 is null

### ISSUE THREAD

**Issue by lfrancke** [watergis/maplibre-gl-export#156]
### Select plugins which related to this issue

maplibre-gl-export

### Bug Description

When trying to generate an export I get this error

```
Uncaught TypeError: i2 is null
    addImage map.ts:2089
    getRenderedMap map-generator.ts:73
    getRenderedMap map-generator.ts:72
    generate map-generator-base.ts:227
    generateMap export-control.ts:208
    onAdd export-control.ts:176
    onAdd export-control.ts:158
    addControl map.ts:736
    <anonymous> main.ts:110
    promise callback* main.ts:71
```

in the console.
All I see is a loading spinner.

I'm sure I'm doing something obvious wrong, I'm unfortunately, a novice at TypeScript/Javascript so I don't think it's a bug but probably me doing something wrong.

I'd appreciate help. Thank you!

This is using maplibre-gl 4.2.0 and maplibre-gl-export 3.7.0.

### Bug Reproduction

1. Go to https://lfrancke.github.io/moorwegsiedlung/
2. Try to export...

The source for this map can be found here: https://github.com/lfrancke/moorwegsiedlung

### Bug System Information

- Browser: Firefox on Arch Linux

**Comment by jmbarbier** [comment]
Same problem here. It seems that data on some images can be null, but still provided to `addImage` by `getRenderedMap`. On my case the map renders on screen without any warning, because the corresponding images are not used, but crashes on exporting with this error. As the `getRenderedMap` add all images from style, even those not used, this error occurs only on exporting.

Adding a check to avoid crashing `addImage` in `getRenderedMap` is enough :

```js
getRenderedMap(e, n) {
    const r = new El({
      container: e,
      style: n,
      center: this.map.getCenter(),
      zoom: this.map.getZoom(),
      bearing: this.map.getBearing(),
      pitch: this.map.getPitch(),
      interactive: !1,
      preserveDrawingBuffer: !0,
      fadeDuration: 0,
      // attributionControl: false,
      // hack to read transfrom request callback function
      // eslint-disable-next-line
      // @ts-ignore
      transformRequest: this.map._requestManager._transformRequestFn
    });
    this.map.getTerrain() && (r.setMaxPitch(85), r.setPitch(this.map.getPitch()));
    const o = (this.map.style.imageManager || {}).images || [];
    return Object.keys(o).forEach((l) => {
      if(o[l].data) {   // ADDED THIS CHECK
        r.addImage(l, o[l].data);
      }                 // ADDED THIS CHECK
    }), r;
  }
```

@JinIgarashi idk if this 'hacky' solution is ok for a pull request.

**Comment by lfrancke** [comment]
Awesome! Thank you for figuring out the problem.

**Comment by JinIgarashi** [comment]
@lfrancke @jmbarbier Thanks for reporting and fixing the issue. I have released new versions for both mapbox and maplibre.
