### ISSUE TITLE
[FEATURE] Option to disable attribution on exported image

### ISSUE THREAD

**Issue by AgentSmith0** [watergis/maplibre-gl-export#168]
### Select plugins which related to this issue

maplibre-gl-export, mapbox-gl-export

### Feature Description

An option to disable the attribution on the exported image (added by default since https://github.com/watergis/maplibre-gl-export/pull/146) would be useful.

**Comment by JinIgarashi** [comment]
yes, I agree an option to disable attribution can be added

**Comment by JinIgarashi** [comment]
@AgentSmith0 done by #169
