### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by vicerator** [watergis/maplibre-gl-export#19]
First of all, congratulations on your plugin because it is amazing.
I think it might be useful for the plugin to have a local Spanish translation, 
so I would like to make that contribution, would that be possible?

**Comment by JinIgarashi** [comment]
@vicerator I am sorry for the late reply. Spanish translation sounds great. Any PRs to add new features or fix bugs on this plugin are welcome.

**Comment by JinIgarashi** [comment]
@vicerator You can fork and make a pull request. Thanks
