### ISSUE TITLE
3D Terrain with MapLibre v.2.2.0-pre.3

### ISSUE THREAD

**Issue by ubukawa** [watergis/maplibre-gl-export#22]
First of all, thank you very much for your great work. I think this is really wonderful work.

**Is your feature request related to a problem? Please describe.**
When I added "maplibre-gl-export" to one of my test map (Terrain map 3D with maplibre v2.2.0-pre.3) and export the image, I was able to export hill shade from raster DEM but I was not able to export terrain 3D. (See the following picture.)

**Describe the solution you'd like**
I would like to have an the same terrain 3D map exported.
I thought it would be done if we updated the version of maplibre-gl to 2.2.0-pre.3 from 2.1.9. (in package.json). I could not build by myself in my local PC because I needed more practice on TypeScript.
Do you have any idea for your future development?

**Describe alternatives you've considered**
Until it support 3D terrain export, I will not add this function to 3D terrain map.
Exporting from 2D map works perfectly.

**Additional context**
Here is some schreenshot.
![2022-07-18-export](https://user-images.githubusercontent.com/59204379/179616884-432eef4f-56ba-4051-be7a-7bfb5bb84716.png)

Thank you!

**Comment by JinIgarashi** [comment]
@ubukawa Thank you for reporting a bug related to 3D terrain feature. I think the repo can upgrade maplibre from 2.1.9 to 2.2.0 if 3D terrain feature is officially released as v2.2.0. Any PR to the repo is most welcome. Please feel free to fork the repo and make a pull request.

**Comment by ubukawa** [comment]
Thank you for sharing your idea! 
I will wait the official release of v2.2.0., and will try to send PR. 
(I will start from installing TypeScript...)

Thank you once again for your great work!!

**Comment by JinIgarashi** [comment]
@ubukawa I have updated maplibre to v2.2.1. Could you try the following version of package?

https://github.com/watergis/maplibre-gl-export/releases/tag/v1.3.6

**Comment by ubukawa** [comment]
Dear @JinIgarashi ,
Thank you for your great work.
I checked the maplibre-gl-export with 3D terrain, but it seems that it did not work well.

Terrain did not appears although the hillshades appeared properly. 
It seems there would be some limitation of max pitch even if I edited it in my html files.

You can see my html files and others.
* MapLibre 2.2.1 with watergis/maplibre-gl-export v1.3.6 
    * https://ubukawa.github.io/nyc-map-test/index-3d.html#10.57/41.023/-73.8611/-32.1/53
* MapLibre 2.2.0-pre.3 with previous version of maplibre-gl-export.
    * https://ubukawa.github.io/nyc-map-test/index-3d-old.html#10.57/41.023/-73.8611/-32.1/53

**Comment by ubukawa** [comment]
When I used tool here:
![image](https://user-images.githubusercontent.com/59204379/184499267-4c191453-93cd-453a-bd5c-71db324f470e.png)

I got an image like this.
![image](https://user-images.githubusercontent.com/59204379/184499297-8ea8f0e2-e120-4539-9748-bc0ad761aed8.png)

**Comment by JinIgarashi** [comment]
@ubukawa I finally managed to add this feature for export plugin. Please try the latest version 3.3.0 of maplibre-gl-export.
