### ISSUE TITLE
[FEATURE] Replacing unmaintained package niklasvh/html2canvas with html2canvas/html2canvas

### ISSUE THREAD

**Issue by AgentSmith0** [watergis/maplibre-gl-export#225]
### Select plugins which related to this issue

maplibre-gl-export, mapbox-gl-export

### Feature Description

The package [html2canvas](https://www.npmjs.com/package/html2canvas) is no longer maintained. What about replacing it with [@html2canvas/html2canvas](https://www.npmjs.com/package/@html2canvas/html2canvas)?

**Comment by JinIgarashi** [comment]
@AgentSmith0 where does this library use html2canvas? If some dependencies are using it, please create an issue for other repositories.
I will close this for now. But feel free to reopen if still there.

**Comment by JinIgarashi** [comment]
@AgentSmith0 ok. I would suggest you to create this issue in the dependent package using html2canvas. I cannot do anything for third party library
