### ISSUE TITLE
maplibre-gl-export and maplibre-gl-legend

### ISSUE THREAD

**Issue by ubukawa** [watergis/maplibre-gl-export#23]
**Describe the bug**
If I added maplibre-gl-legend.js to a webmap with maplibre-gl-export, I found that the export button disappeared.

**To Reproduce**
1. Go to 'https://ubukawa.github.io/nyc-map-test/index-test00.html', you will see the export button on top right. 
2. Then, edit html file to add a module for maplibre-gl-legend: https://github.com/ubukawa/nyc-map-test/blob/main/docs/index-test01.html#L12-L15
3. Go to 'https://ubukawa.github.io/nyc-map-test/index-test01.html', you will NOT see the export button on top right. 

**Expected behavior**
Both legend and export buttons there.

![image](https://user-images.githubusercontent.com/59204379/180291030-d613de3c-0930-4055-9e77-8d2d68b1d53b.png)

**Comment by JinIgarashi** [comment]
@ubukawa It’s the same error with this issue

https://github.com/watergis/mapbox-gl-legend/issues/20

There is an issue using CDN version. You can use npm to install both library alternatively. It works well.

however, welcome to make a PR to fix this issue. Thanks

**Comment by ubukawa** [comment]
Oh, thank you! I was not aware of the issue at the other side. I am so sorry.
I will check them or will use npm. Thank you.

**Comment by JinIgarashi** [comment]
@ubukawa and @AgentSmith0. namespace were removed from CDN for both export and legend plugins. Could you try the following version' CDNs?

- https://github.com/watergis/maplibre-gl-export/releases/tag/v1.3.5
- https://github.com/watergis/maplibre-gl-legend/releases/tag/v1.2.5

**Comment by ubukawa** [comment]
I have confirmed that both plugin appear properly! Thank you, @AgentSmith0  and @JinIgarashi !
https://ubukawa.github.io/nyc-map-test/index-test02.html
