### ISSUE TITLE
[BUG] Unable to push to my own forked repo

### ISSUE THREAD

**Issue by erictheise** [watergis/maplibre-gl-export#243]
### Select plugins which related to this issue

maplibre-gl-export

### Bug Description

I'm merely trying to get started using a fork of your project. The only change to my code base was a bump of `pnpm` from 9.0.0 to 9.9.0.

My output is

```
 % git push
╭─────────────────────────────────────╮
│ 🥊 lefthook v1.7.14  hook: pre-push │
╰─────────────────────────────────────╯
┃  build ❯ 


> @watergis/maplibre-gl-export@1.0.0 build /Users/erictheise/Repos/erictheise/maplibre-gl-export
> pnpm -r build

Scope: 3 of 4 workspace projects
packages/maplibre-gl-export build$ 
[10 lines collapsed]
│ 

│ 
└─ Done in 2.7s
packages/mapbox-gl-export build$ 
[10 lines collapsed]
│ 

│ 
└─ Done in 3.9s
sites/demo build$ 
│ 

│ 
└─ Failed in 3s at /Users/erictheise/Repos/erictheise/maplibre-gl-export/sites/demo
/Users/erictheise/Repos/erictheise/maplibre-gl-export/sites/demo:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  demo@0.0.1 build: `vite build`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.

                                      
  ────────────────────────────────────
summary: (done in 10.21 seconds)      
🥊  build
error: failed to push some refs to 'github.com:erictheise/maplibre-gl-export.git'
erictheise@Erics-MacBook-Pro maplibre-gl-export % 
```

I am unfamiliar with your build regime but I notice the build badge is missing from your repo.

### Bug Reproduction

Install `corepack` via homebrew.
Follow the steps in `CONTRIBUTING.md`. 

### Bug System Information

- OS: MacOS 14.6.1
- Node: v20.15.1

**Comment by JinIgarashi** [comment]
@erictheise interesting. I am not sure what’s wrong with your environment. It looks good for my computer…

**Comment by erictheise** [comment]
@JinIgarashi, you, no doubt, have a `sites/demo/.env` file. I did not, and the build was failing here–

```
│ 12:   import { PUBLIC_MAPBOX_ACCESSTOKEN } from '$env/static/public'; [10 lines collapsed]
│                ^
```

My opinion: someone who wants to develop/extend the library shouldn't be forced to build demo sites; that should be its own distinct and non-mandatory task. If you disagree then the documentation should warn people of this and nudge them to copy `env.example` to `.env`.

For anyone else who bumps into this, `PUBLIC_MAPBOX_ACCESSTOKEN` does not need to take a value it just needs to appear in the `.env` file. I'm not even sure why it's even required when the point of this library is to move away from Mapbox.

**Comment by JinIgarashi** [comment]
@erictheise access token is required for Mapbox since v2. Documentation covers both maplibre and mapbox. There is no way to remove mapbox token. You can create an account in mapbox to get a token.

**Comment by erictheise** [comment]
FWIW, I've had a Mapbox account since 2012 and have generated my share of tokens over the years. I asked you about a few things but I did not ask you to remove the Mapbox token.
