### ISSUE TITLE
Lib / dist file error

### ISSUE THREAD

**Issue by rbraggaar** [watergis/maplibre-gl-export#29]
**Describe the bug**

Lib folder is not present when you install the module, but it seems to reference some files from this folder. These files do exist in the dist folder though.

**Error: ENOENT: no such file or directory, open '<MY_APP_PATH>\node_modules\@watergis\maplibre-gl-export\lib\crosshair-manager.ts'**

```
WARNING in ./node_modules/@watergis/maplibre-gl-export/dist/crosshair-manager.js

Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):

Failed to parse source map from '<MY_APP_PATH>\node_modules\@watergis\maplibre-gl-export\lib\crosshair-manager.ts'** file: 

Error: ENOENT: no such file or directory, open '<MY_APP_PATH>\node_modules\@watergis\maplibre-gl-export\lib\crosshair-manager.ts'
```
![image](https://user-images.githubusercontent.com/16044244/225904636-9a65b9c5-4bc8-493b-9730-2e6c975218f8.png)

**Additional context**
React 18.2.0 using webpack.

**Comment by JinIgarashi** [comment]
@rbraggaar I have updated my plugin by migrating webpack to vite. The folder structure was changed significantly. could you check this issue with the latest version?

**Comment by rbraggaar** [comment]
@JinIgarashi updated to 2.0.1 and this specific issue seems to be resolved now.
However, I no longer see the printable area nor the crosshair though.

Importing the css like so, is that correct?
`import "@watergis/maplibre-gl-export/dist/maplibre-gl-export.css";`

**Comment by JinIgarashi** [comment]
@rbraggaar Yes, css importing is correct. I am not sure why printable area is not working. It works in demo site. Anyway,let me close this issue. You can create new issue for printable area. Thanks
