### ISSUE TITLE
Uncaught TypeError: MaplibreExportControl is not a constructor

### ISSUE THREAD

**Issue by 2803media** [watergis/maplibre-gl-export#42]
With last version and the example provided with cdn I've got this error:

`Uncaught TypeError: MaplibreExportControl is not a constructor`

**Comment by JinIgarashi** [comment]
@2803media 
For CDN, please try `MaplibreExportControl. MaplibreExportControl`. The example on readme is missing namespace. Feel free to make PR to update readme.

**Comment by 2803media** [comment]
PR send!
